name: ai4db
channels:
  - conda-forge
  - defaults
  - pytorch

dependencies:
  # ============================================================================
  # PYTHON VERSION
  # ============================================================================
  - python=3.10.*

  # ============================================================================
  # CORE SCIENTIFIC COMPUTING
  # ============================================================================
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.10.0

  # ============================================================================
  # DEEP LEARNING (PyTorch for CTGAN and transformers)
  # ============================================================================
  # For CPU-only (eclab):
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - cpuonly
  
  # For GPU (ipazia) - comment out cpuonly above and uncomment below:
  # - pytorch>=2.0.0
  # - torchvision>=0.15.0
  # - pytorch-cuda=11.8

  # ============================================================================
  # DATA SCIENCE AND UTILITIES
  # ============================================================================
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - tqdm>=4.66.0

  # ============================================================================
  # WEB AND API
  # ============================================================================
  - requests>=2.31.0
  - urllib3>=2.0.0

  # ============================================================================
  # JUPYTER (for experimentation)
  # ============================================================================
  - jupyter>=1.0.0
  - ipython>=8.0.0
  - notebook>=7.0.0

  # ============================================================================
  # CODE QUALITY (optional but recommended)
  # ============================================================================
  - black>=23.0.0
  - flake8>=6.0.0

  # ============================================================================
  # PIP PACKAGES (not available via conda or newer versions needed)
  # ============================================================================
  - pip>=23.0.0
  - pip:
      # SDV - Synthetic Data Vault (Stage 2)
      - sdv==1.9.0
      
      # SQL parsing (Stage 2)
      - sqlparse==0.4.4
      
      # Sentence transformers (Stage 3 - semantic similarity)
      - sentence-transformers>=2.2.2
      
      # Transformers (Stage 3 - paraphrasing, back-translation)
      - transformers>=4.35.0
      - tokenizers>=0.15.0
      - huggingface-hub>=0.19.0
      - safetensors>=0.4.0
      - accelerate>=0.24.0
      
      # NLP utilities
      - nltk>=3.8.0
      
      # Validation
      - jsonschema>=4.19.0
      
      # Date utilities
      - python-dateutil>=2.8.0
      
      # Optional: Grammar checking (Stage 3 quality control)
      # Uncomment if needed (heavy dependency):
      # - language-tool-python>=2.7.1

# ============================================================================
# INSTALLATION NOTES
# ============================================================================

# For eclab (CPU-only):
# conda env create -f environment.yml
# conda activate ai4db

# For ipazia (GPU):
# 1. Edit this file and uncomment the GPU lines (pytorch-cuda)
# 2. Comment out the cpuonly line
# 3. conda env create -f environment.yml
# 4. conda activate ai4db

# To update existing environment:
# conda env update -f environment.yml --prune

# To export your current environment:
# conda env export > environment_backup.yml

